// <auto-generated />
namespace CarsInventory.DataContext.InventoryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddInventory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInventory));
        
        string IMigrationMetadata.Id
        {
            get { return "201507250528287_Add Inventory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
